### PR TITLE
Update build number

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by certik** [comment]
Now when this got merged, if I want to test the new package, how do I do that? I tried
```
$ conda install -c conda-forge dftatom
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
```
But it doesn't seem to pick up the new package.

**Comment by isuruf** [comment]
Try `conda update -c conda-forge dftatom`

**Comment by certik** [comment]
Same thing:
```
$ conda update -c conda-forge dftatom
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
```

**Pull request merged**
